service:
  type: ClusterIP
  port: 6379

replica:
  replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

networkPolicy:
  enabled: true

metrics:
  enabled: true